# Generated by Django 4.1.3 on 2022-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_description_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="default-blog-banner.jpg", upload_to="blog_pics"
            ),
        ),
    ]
