# Generated by Django 4.1.3 on 2022-12-04 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
