# Generated by Django 4.1.3 on 2022-12-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_created"]},
        ),
    ]
