# Generated by Django 4.1.3 on 2022-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(
                default="Your awesome profile", max_length=250, null=True
            ),
        ),
    ]
