# Generated by Django 4.1.3 on 2022-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(
                default="Just me, myself and I, exploring the universe of uknownment. I have a heart of love and a interest of lorem ipsum and mauris neque quam blog. I want to share my world with you.",
                max_length=250,
                null=True,
            ),
        ),
    ]
